### ISSUE TITLE
All files and folders should be lowercase, hyphen separated

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/guides#8]
Please use lowercase for the names of all markdown files and folders (images are ok).
- `GPIO` should be `gpio`
- `pi_in_the_sky` should be `pi-in-the-sky`

and so on.

And update links accordingly.

**Comment by MarcScott** [comment]
Closing as pedantic - update to guides coming soon

**Comment by bennuttall** [comment]
This isn't live anywhere, you can archive it and close issues
