### ISSUE TITLE
Getting-started guide is out of date

### ISSUE THREAD

**Issue by jeff5** [raspberrypilearning/guides#9]
The getting-started guide is out of date compared with the behaviour of a newly-downloaded NOOBS 1.5, which now gives you an OS that boots directly to a desktop. As the guide is the basis of the first documentation a Pi beginner (that's me) finds on the RPi site, it should align with what people will actually see. Users should also be directed to the graphical replacement for raspi-config.

Assuming I can master the mechanics, I'll offer you changed words in a pull request. I guess accepting this won't automatically update the site (or the video).

**Comment by MarcScott** [comment]
@caitlynraspberrypi can you update https://github.com/raspberrypilearning/guides/blob/master/pi/writing-sd-card-image.md to reflect current install of noobs on the RPi 3+ please

**Comment by martinohanlon** [comment]
@marc I recommend we close this issue, the old "getting started guide" will be replaced shortly with:

https://projects.raspberrypi.org/en/projects/raspberry-pi-setting-up

**Comment by jeff5** [comment]
Fine by me.
